#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 08:00:00
#SBATCH -J HTSeq_May6th
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

#Final  Using HTSeq-counts to do differential analysis
set -x
echo QOS = $SLURM_JOB_QOS

# make new directory for FastQ files
mkdir /proj/genomeanalysis2022/nobackup/work/erikpalm/htseq_$SLURM_JOB_ID
cd /proj/genomeanalysis2022/nobackup/work/erikpalm/htseq_$SLURM_JOB_ID

# copying multiple files to external directory 
export SRCDIR=$HOME

# making directory within storage node
cd $SNIC_TMP
mkdir Prokka_gff
mkdir Mapping
mkdir output
mkdir Assembled_data

# copying multiple files to external directory
cp  /home/erikpa/Genome_Analysis_Project_2022/Analysis/Prokka_6186474/PROKKA_05062022/PROKKA_04192022_withoutfasta.gff \
$SNIC_TMP/Prokka_gff
cp  /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_6188139/* $SNIC_TMP/Mapping
cp  /home/erikpa/Genome_Analysis_Project_2022/Data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Assembled_data 

# Load modules
module load bioinfo-tools
module load htseq
module load bwa
module load samtools

# Going into output

# copy index files to mapping folder
cp $SNIC_TMP/Assembled_data/* $SNIC_TMP/Mapping

#move into mapping folder
cd $SNIC_TMP/Mapping
samtools index $SNIC_TMP/Mapping/*629*
samtools index $SNIC_TMP/Mapping/*630*
samtools index $SNIC_TMP/Mapping/*631*
samtools index $SNIC_TMP/Mapping/*632*
samtools index $SNIC_TMP/Mapping/*633*

# Doing HTSeq. Experiments come from two different environmental groups, the continuous treatment and the mineral.
# These are treated separately.

# maybe three inputs won't work
htseq-count -f bam -s no -i ID  -r pos -t CDS $SNIC_TMP/Mapping/ERR2036629_sorted.bam $SNIC_TMP/Mapping/ERR2036630_sorted.bam $SNIC_TMP/Mapping/ERR2036631_sorted.bam $SNIC_TMP/Prokka_gff/PROKKA_04192022_withoutfasta.gff > continuous
htseq-count -f bam -s no -i ID  -r pos -t CDS $SNIC_TMP/Mapping/ERR2036629_sorted.bam $SNIC_TMP/Mapping/ERR2036633_sorted.bam $SNIC_TMP/Prokka_gff/PROKKA_04192022_withoutfasta.gff > mineral


# Returning to external storage
cp $SNIC_TMP/Mapping/* /proj/genomeanalysis2022/nobackup/work/erikpalm/htseq_$SLURM_JOB_ID
