#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 02:00:00
#SBATCH -J Post_Trimmed_May_6th
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

# Using FastQC on all of the Trimmed Reads
set -x

# make new directory for FastQ files
mkdir /home/erikpa/Genome_Analysis_Project_2022/Analysis/FASTQ_posttrim_$SLURM_JOB_ID
cd /home/erikpa/Genome_Analysis_Project_2022/Analysis/FASTQ_posttrim_$SLURM_JOB_ID

# copying multiple files to external directory 
export SRCDIR=$HOME

# making directory within storage node
cd $SNIC_TMP
mkdir RNA_trimmed_data
mkdir output

# copying multiple files to external directory
cp  /home/erikpa/Genome_Analysis_Project_2022/Analysis/Trimming_Raw_Reads_Trimmomatic_6186484/*.fq* \
$SNIC_TMP/RNA_trimmed_data

# Load modules
module load bioinfo-tools
module load FastQC

# Going into output

fastqc -o $SNIC_TMP/output -f fastq $SNIC_TMP/RNA_trimmed_data/*

# Returning to external storage
cp $SNIC_TMP/output/* /home/erikpa/Genome_Analysis_Project_2022/Analysis/FASTQ_posttrim_$SLURM_JOB_ID
