#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:15:00
#SBATCH -J CHANGECHANGECHANGECHANGECHANGE
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com
# Load modules
module load bioinfo-tools
module load FastQC
