#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 07:00:00
#SBATCH -J BWA_Using_Trimmomatic_Trimmed_Reads_Apr28
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

# Using BWA to map and align RNA reads onto Assembled Genome to assess.
set -x
echo QOS = $SLURM_JOB_QOS

# make new directory for FastQ files
mkdir /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID
cd /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID

# copying multiple files to external directory 
export SRCDIR=$HOME

# making directory within storage node
cd $SNIC_TMP
mkdir Assembled_data
mkdir Trimmed_RNA_Reads
mkdir output

# copying multiple files to external directory
cp  /home/erikpa/Genome_Analysis_Project_2022/Data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Assembled_data
cp  /home/erikpa/Genome_Analysis_Project_2022/Analysis/Trimming_Raw_Reads_Trimmomatic_6186484/* $SNIC_TMP/Trimmed_RNA_Reads
 
# Load modules
module load bioinfo-tools
module load bwa
module load samtools

cd $SNIC_TMP/Trimmed_RNA_Reads
ls
# Going into output
cd $SNIC_TMP/Assembled_data

# Indexing genome
bwa index $SNIC_TMP/Assembled_data/*

# doing the actual mapping 
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036629_1_output_forward_paired.fq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036629_2_output_reverse_paired.fq.gz | samtools sort -o ERR2036629_sorted.bam
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036630_1_output_forward_paired.fq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036630_2_output_reverse_paired.fq.gz | samtools sort -o ERR2036630_sorted.bam
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036631_1_output_forward_paired.fq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036631_2_output_reverse_paired.fq.gz | samtools sort -o ERR2036631_sorted.bam
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036632_1_output_forward_paired.fq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036632_2_output_reverse_paired.fq.gz | samtools sort -o ERR2036632_sorted.bam
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036633_1_output_forward_paired.fq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036633_2_output_reverse_paired.fq.gz | samtools sort -o ERR2036633_sorted.bam

# Returning to external storage
cp $SNIC_TMP/Assembled_data/*2036* /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID
