#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:20:00
#SBATCH -J RNA_Test_5_Apr
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

set -x

# mkdir
mkdir /home/erikpa/Genome_Analysis_Project_2022/Analysis/test_$SLURM_JOB_ID
cd /home/erikpa/Genome_Analysis_Project_2022/Analysis/test_$SLURM_JOB_ID

# copying multiple files to external directory (need softlink)


export SRCDIR=$HOME
# making directory within storage node
cd $SNIC_TMP
mkdir RNA_raw_data
mkdir output

# Load modules
module load bioinfo-tools
module load FastQC


WORKDIR=/home/erikpa/Genome_Analysis_Project_2022/Analysis/test_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cd "$WORKDIR" || exit -1


# Unzipping Sequencing Files
for f in $SNIC_TMP/sequence_data/*
do
  	echo "$f"
        gunzip "$f"
done

cd ..
# Going into output
cd $SNIC_TMP/output\
fastqc -f -o "$WORKDIR" -f fastq /home/erikpa/Genome_Analysis_Project_2022/Data/RNA_raw_data/ERR2036629_1.fastq.gz

Returning to external storage
cp $SNIC_TMP/output/* 
# None in this case because it's not important
