#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:05:00
#SBATCH -J Synten_Apr21
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

# It works! Using blastn to compare the assembled genome with a complete genome found from NCBI.
# Does not use local storage because I could not get it to work
set -x
echo QOS = $SLURM_JOB_QOS

cd /home/erikpa/Genome_Analysis_Project_2022/Analysis
mkdir blastn_$SLURM_JOB_ID

# Load modules
module load bioinfo-tools
module load blast

# Going into output
cd /home/erikpa/Genome_Analysis_Project_2022/Analysis/blastn_$SLURM_JOB_ID

blastn -query /home/erikpa/Genome_Analysis_Project_2022/Data/assembled_L.ferri_1_4.contigs.fasta \
 -subject /home/erikpa/Genome_Analysis_Project_2022/Data/CP002919.1.fa -out blastn_results_$SLURM_JOB_ID -outfmt 7	
