#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J BWA_Testing_to_see_if_something_problematic_with_files_28_Apr
#SBATCH --mail-type=ALL
#SBATCH --mail-user erikspencereverett@gmail.com

# Using BWA to map and align RNA reads onto Assembled Genome to assess.
set -x
echo QOS = $SLURM_JOB_QOS

# make new directory for FastQ files
mkdir /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID
cd /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID

# copying multiple files to external directory 
export SRCDIR=$HOME

# making directory within storage node
cd $SNIC_TMP
mkdir Assembled_data
mkdir Trimmed_RNA_Reads
mkdir output

# copying multiple files to external directory
cp  /home/erikpa/Genome_Analysis_Project_2022/Data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Assembled_data
cp  /proj/genomeanalysis2022/Genome_Analysis/2_Christel_2017/RNA_trimmed_reads/* $SNIC_TMP/Trimmed_RNA_Reads
 
# Load modules
module load bioinfo-tools
module load bwa
module load samtools

# Going into output
cd $SNIC_TMP/Assembled_data

# Indexing genome
bwa index $SNIC_TMP/Assembled_data/*

# doing the actual mapping 
bwa mem -t 2 $SNIC_TMP/Assembled_data/assembled_L.ferri_1_4.contigs.fasta $SNIC_TMP/Trimmed_RNA_Reads/ERR2036629_P1.trim.fastq.gz $SNIC_TMP/Trimmed_RNA_Reads/ERR2036629_P2.trim.fastq.gz | samtools sort -o ERR2036629_sorted.bam

# Returning to external storage
cp $SNIC_TMP/Assembled_data/*2036* /home/erikpa/Genome_Analysis_Project_2022/Analysis/BWA_$SLURM_JOB_ID
